### ISSUE TITLE
Return is undefined

### ISSUE THREAD

**Issue by seanmavley** [JcBernack/meteor-reactive-aggregate#1]
This is my publish:

```
Meteor.publish("reportTotals", function() {
var theHours = ReactiveAggregate(this, Reports, [{
    $group: {
        '_id': this.userId,
        'hours': {
            $sum: '$hours'
        },
        'magazines': {
            $sum: '$magazines'
        },
        'brochures': {
            $sum: '$brochures'
        },
        'books': {
            $sum: 'books'
        }
    }
}, {
    $project: {
        userId: '$_id',
        hours: '$hours',
        magazines: '$magazines',
        brochures: '$brochures',
        books: '$books'
    }
}]);

console.log(theHours);
```

});

In console, I get the response: `undefined`

I might be missing something

**Comment by JcBernack** [comment]
Nope, you're not missing something. `ReactiveAggregate` does not return anything. The result of the aggregation is pushed directly to the client, see the second example here: http://docs.meteor.com/#/full/meteor_publish

You should check if the correct data is available on the client after subscribing.

**Comment by seanmavley** [comment]
Thanks. At the moment, I have this done:

```
Meteor.publish("reportTotals", function() {
    ReactiveAggregate(this, Reports, [{... }]);
});
```

If the Aggregated result is appended to client collection, how do I access them?

I am subscribed as 

```
  Meteor.subscribe('reportTotals');
```

In my template helper, I reference the reportTotals like so:

```
Template.statsBrief.helpers({
    reportTotals: function() {
        console.log('success');
        return Reports.find();
    },
});
```

Then in the template, as in `<template name="statsBrief"> ... </template>`, how do I access the results of the aggregate?

thanks

**Comment by JcBernack** [comment]
All this looks good to me, you would access it as always, e.g. `{{#each reportTotals}}`.
The only problem I see is that your projection stage leaves the documents without an `_id` property. If that is true you must change that, this package and basically the whole DDP protocol requires an _id on all documents.

**Comment by seanmavley** [comment]
Awesome. Aggregation shows in template, this time, with the other aggregated rows. See image:

![screenshot from 2015-12-23 18-52-08](https://cloud.githubusercontent.com/assets/5289083/11982817/7f864a8c-a9a6-11e5-95df-af08e550d397.png)

In the above image, the last column on the right is the aggregation object, aggregated from the two objects on the left. 

When I do the `{{#each reportTotals}}{{hours}}{{/each}}` for instance, I get `105060`. Any idea why? And if  sending the aggregated results into a client side collection on the fly will do, how do I do that? Passing in the `options`, I'm struggling to as I don't know the right way to pass it in.

**Comment by JcBernack** [comment]
Oh, I see. The aggregated result is appended to the same collection as the documents used by the aggregation. For that case I would recommend adding the aggregated result to a different client-side collection using the `clientCollection` option like so:

```
Meteor.publish("reportTotals", function() {
    ReactiveAggregate(this, Reports, [{... }], { clientCollection: "reportsTotal" });
});
```

This collection is only needed on the client:

```
ReportTotals = new Mongo.Collection("reportsTotal");
```

I have not tested this feature yet, but in theory it should work ;-)

**Comment by seanmavley** [comment]
Thank you very much JcBernack. Got it working, `reactively`. Its just amazing. 
Added some more text to the readme to help newbies like myself get started easier and sent in a PR. I hope its good enough to help new ones figure it out nicely.

**Comment by JcBernack** [comment]
Great, thanks for the PR! :)
