### ISSUE TITLE
Error with Meteor 1.3.2.4

### ISSUE THREAD

**Issue by manhhailua** [JcBernack/meteor-reactive-aggregate#10]
`import {ReactiveAggregate} from 'meteor/jcbernack:reactive-aggregate';`

This is my publish function.

> Meteor.publish('skills', () => {
> return ReactiveAggregate(this, Skills, [
> {$match: {status: 'active'}},
> {$limit: 10}
> ]);
> });

And in the meteor console I got this:
`I20160422-16:12:21.076(7)? Exception from sub skills id RE76noLCSJ2LeaYeh TypeError: Object [object global] has no method 'added'`
`I20160422-16:12:21.078(7)?     at packages/jcbernack_reactive-aggregate/aggregate.js:17:1`
`I20160422-16:12:21.079(7)?     at Array.forEach (/home/manhpt/.meteor/packages/es5-shim/.4.5.10.ajfzqv++os+web.browser+web.cordova/npm/node_modules/es5-shim/es5-shim.js:435:21)`
`I20160422-16:12:21.080(7)?     at update (packages/jcbernack_reactive-aggregate/aggregate.js:15:1)`
`I20160422-16:12:21.081(7)?     at ReactiveAggregate (packages/jcbernack_reactive-aggregate/aggregate.js:47:1)`
`I20160422-16:12:21.083(7)?     at Subscription._handler (imports/api/skills.js:20:12)`
`I20160422-16:12:21.084(7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)`
`I20160422-16:12:21.085(7)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)`
`I20160422-16:12:21.086(7)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)`
`I20160422-16:12:21.088(7)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)`
`I20160422-16:12:21.089(7)?     at packages/ddp-server/livedata_server.js:551:43`

My app was fine but the result of subscribe method became empty. The problem happend the same to collection:users `Meteor.users`.

**Comment by JcBernack** [comment]
You can't use the ES6 arrow function here, use a normal function because the this-context is needed.

**Comment by manhhailua** [comment]
Thank you! Problem's solved!
Hope you will update this package soon!
