### ISSUE TITLE
how to get a correct subscription.ready() ?

### ISSUE THREAD

**Issue by hungchai** [JcBernack/meteor-reactive-aggregate#11]
First of all, this package is great.Thanks. But I have trouble when getting correct subscription ready() value. The ready() is always kept to false status. How can I know the subscription is ready?

**Comment by sunlee-newyork** [comment]
^ I have the same question, wish this issue wasn't closed without an answer. My `Meteor.subscribe('some_aggregate_pub').ready()` always returns false if cursor returns empty. Any help would be appreciated!
