### ISSUE TITLE
Problem with "$lookup"?

### ISSUE THREAD

**Issue by thearabbit** [JcBernack/meteor-reactive-aggregate#12]
I use `$lookup` aggregate function in `Mongo 3.2`.

``` js
ReactiveAggregate(this, Disbursement, [
        {$match: {_id: _id}},
        {
            $lookup: {
                from: "loan_client",
                localField: "clientId",
                foreignField: "_id",
                as: "clientDoc"
            }
        },
        {$unwind: "$clientDoc"},
.............
```

It don't work when I tried to change `client info`.

**Comment by JcBernack** [comment]
This package observes changes in the given collection (`Disbursement`) and updates the aggregation. Changes to the collection used by `$lookup` will go unnoticed. Maybe you should push the other collections via separate publications and "join" on the client side.

**Comment by thearabbit** [comment]
Thanks for your reply.
Could example?

**Comment by crapthings** [comment]
@thearabbit 

collection.js

```
Posts = new Mongo.Collection('posts')

Meteor.isServer && Meteor.publish('posts', function() {
  // ReactiveAggregate(this, Posts, [{
  //   $lookup: {
  //     from: 'users',
  //     localField: 'userId',
  //     foreignField: '_id',
  //     as: 'user'
  //   }
  // }])

  return [Posts.find(), Users.find()]
})
```

client.js

```
Template.registerHelper('posts', function () {
  return Posts.find().map(post => {
    return _.extend(post, {
      user: Users.find(post.userId)
    })
  })
})
```

**Comment by apathio** [comment]
@crapthings 

Thanks for posting this example. The reduction and flexibility of my code changes in relation to publications (publish composite, reactive join aggregations), coupled using react-komposer, simply exquisite. Fair amount of unbounded arrays requiring aggregations, so denormalizing was not a very good option (or really much of an option at all). This solved a ton of problems and helped me think of a couple of new ways to do things. Thanks again!

**Comment by psaelango** [comment]
@JcBernack - Is there any way to get reactivity of collection used by $lookup? I'm in a situation that I cannot use your above proposed solution that "publish other collections and join them on client side". Because of the huge amount of data in the other collection I cannot publish them. At the same time I need to aggregate with that collection data. Your suggestions would be very much appreciated
