### ISSUE TITLE
how to use with match date aggregate?

### ISSUE THREAD

**Issue by syafiqFiqq** [JcBernack/meteor-reactive-aggregate#13]
i have this line of code.. 
`
$match: { createdAt: {$gte: new Date(dateFrom), $lte: new Date(dateTo)} },
        $group: {
            '_id': "$userName",
            'points': {
            // In this case, we're running summation.
                $sum: '$points'
            },
            'reportCount': {
                $sum: 1
            }
        }
`

how to approach this ?

**Comment by JcBernack** [comment]
I'm sorry, but with this little information I can't help you.
