### ISSUE TITLE
clientCollection name not defined on client side

### ISSUE THREAD

**Issue by experiencedigital** [JcBernack/meteor-reactive-aggregate#14]

**Comment by prinzdezibel** [comment]
Had the same problem and you need to ensure that:
1) Your server side publish method is actually executed (especially when using the new ES2015 import mechanism where there's lazy loading involved).
2) Your publish function does not interfere with meteor's autopublish. IMHO, this feature shouldn't exist at all. To avoid pulling your hair out at a later time disable it right from the start: `meteor remove autopublish`.
