### ISSUE TITLE
clientCollection name not defined on client side

### ISSUE THREAD

**Issue by adamstickley** [JcBernack/meteor-reactive-aggregate#15]
I have what I thought was a relatively simple test, but I'm not sure where I'm going wrong. The lookup itself works with the regular aggregate function.

```
Meteor.publish('allPropertyApps', function() {
ReactiveAggregate(this, applicationsTable, [
    {
        $lookup: {
            from: "partyGroups",
            localField: "owner",
            foreignField: "_id",
            as: "application_party"
        }
    }
], { clientCollection: "propApps" });
```

but when I attempt to access "propApps" in my helper, it's undefined.

```
class PropertyApplications {
    constructor($scope, $stateParams) {
        'ngInject';

        $scope.viewModel(this);

        this.$scope = $scope;
        this.$stateParams = $stateParams;

        this.$scope.propertyId = this.$scope.propertyApplications.property._id;
        if(this.$scope.propertyId === undefined) {
            this.$scope.propertyId = this.$stateParams.pid;
        }
        Meteor.subscribe('allPropertyApps', this.$scope.propertyId);

        this.helpers({
            allPropertyApps: function () {
                console.log('working!');
                console.log(propApps);
                return propApps.find();
                return false;
            }
        });
    }
}
```

If I define "propApps" within a client-side collection myself, then it just stays as an empty collection.

**Comment by JcBernack** [comment]
Where exactly are you defining the `propApps` collection and how are you accessing it from this code? I haven't used Meteor for a while now and I'm still used to the "everything is global" style of Meteor 1.2. Your code uses ES6 features so I guess you're on a newer version of Meteor and need to properly import the collection?

**Comment by JcBernack** [comment]
Using Mongos `$lookup` can cause problems with this package, because changes in the other collection do not trigger an update. See #12.

**Comment by prinzdezibel** [comment]
Had the same problem and you need to ensure that:
1) Your server side publish method is actually executed (especially when using the new ES2015 import mechanism where there's lazy loading involved).
2) Your publish function does not interfere with meteor's autopublish. IMHO, this feature shouldn't exist at all. To avoid pulling your hair out at a later time disable it right from the start: `meteor remove autopublish`.
