### ISSUE TITLE
May be this is a bug

### ISSUE THREAD

**Issue by hungchai** [JcBernack/meteor-reactive-aggregate#16]
This code has problem

> sub._ids[doc._id] = sub._iteration;

If doc._id is mongo ObjectID type, then sub.ids[] will stored "ObjectId('57980bccc33da59766a6e806')" as key, but  

> sub.added(options.clientCollection,doc._id, doc); 

sub will pick '57980bccc33da59766a6e806' as key of publish document, so it will throw exception during  sub.removed() as k = ObjectId('57980bccc33da59766a6e806') does not match  as 57980bccc33da59766a6e806

> ```
> if (v != sub._iteration) {
>         delete sub._ids[k];
>         sub.removed(options.clientCollection, k);
>       }
> ```

```

function update() {
    if (initializing) return;
    // add and update documents on the client
    collection.aggregate(pipeline).forEach(function (doc) {
      if (!sub._ids[doc._id]) {
        sub.added(options.clientCollection, doc._id, doc);
      } else {
        sub.changed(options.clientCollection, doc._id, doc);
      }
      sub._ids[doc._id] = sub._iteration;
    });
    // remove documents not in the result anymore
    _.forEach(sub._ids, function (v, k) {
      if (v != sub._iteration) {
        delete sub._ids[k];
        sub.removed(options.clientCollection, k);
      }
    });
    sub._iteration++;
  }

```

**Comment by JcBernack** [comment]
If you mix string-id and Mongo-ObjectID within a collection you're going to have problems, not only with this package. Make sure you stick to one or the other and it should work just fine.

**Comment by hungchai** [comment]
Thanks for your reply. 
If I just use match query in Aggregation pipeline, it will throw exception in your case, To fix it, I have to project a new _id with string-id. Do you mean it is normal?

**Comment by JcBernack** [comment]
No, that is not normal. You should not have this problem if you are using string-ids everywhere. If I remember correctly Meteor inserts only strings as ids by default, but somehow you got ObjectIDs in your collection which is problematic. I once had a similar problem after inserting some documents directly into a collection via the Mongo shell, because Mongo inserts ObjectIDs by default.

**Comment by hungchai** [comment]
Yes, you are right as my collection data areprepared by the other nodejs task. So the ids should be ObjectIDs by default. Could you add a datatype checking to _id? Thanks.
