### ISSUE TITLE
Efficiency is very low? Why?

### ISSUE THREAD

**Issue by violetbobo** [JcBernack/meteor-reactive-aggregate#18]
I test this package, just using simple pipeline:

```
ReactiveAggregate(this, loanLogs, [{
    $match: {
        own:user.username,
        time: {
            $gt: new Date("2016-09-01")
        }
    }
}], {
    clientCollection: "todayLoanTotal"
});
```

It works, but not well, costing 10s~20s to get data at first time .
Then debug your code , 

```
var handle = query.observeChanges({
    added: update,
    changed: update,
    removed: update,
    error: function (err) {
      throw err;
    }
});
```

`observeChanges` is blocked for 10~20 seconds. Why? Do I miss something esle? Thanks!

**Comment by JcBernack** [comment]
The idea behind this package is in fact not that efficient. It "emulates" reactive aggregations by re-evaluating the whole aggregation every time any data which might effect the result changes. By default this means "any changes to the collection" to work out of the box, but it can and should be limited to a relevant part of the collection by using the `observeSelector` option.

During initialization the `observeChanges` method unfortunately fires an `added` event for each document in the result set of `observeSelector`. These events are all skipped, but I can image that performance will suffer if the collection has lots of documents.

Supplying a good `observeSelector` therefore will not only reduce the number of redundant aggregations but will probably also reduce the long startup time you are experiencing.

**Comment by tim-phillips** [comment]
How does one utilize the `observeSelector`? Once I grok this I wouldn't mind making a PR to add this to the docs. 

EDIT: I figured this out. The `observeSelector` and `observeOptions` are what are entered into the query at the following location:

https://github.com/JcBernack/meteor-reactive-aggregate/blob/683f6817d610ba3e1167a534dbb5cbae32abf395/aggregate.js#L35

I'm seeing _vast_ improvements in speed and efficiency.

**Comment by JcBernack** [comment]
Thanks for the PR @babenzele.

Depending on the number of documents in the collection the `observeSelector` is crucial for performance, but keep in mind that you can also easily break reactivity of the aggregated results.
