### ISSUE TITLE
Subscribe.ready() doesn't turn true with empty results

### ISSUE THREAD

**Issue by sunlee-newyork** [JcBernack/meteor-reactive-aggregate#25]
Hi there,

I'm opening this issue as follow-up to Issue #11 regarding the subscription `.ready()` method. My `Meteor.subscribe('some_aggregate_pub').ready()` always returns false if the aggregate has no `$match` results. Is there a work-around to check if there are no results and the subscription is ready?

Thank you!

**Comment by dellasys** [comment]
Add the ready() in the createContainer and use the props.menuListSubReady in the component may solve the issue.

Example :   
```
createContainer(() => {
      const menuListSub = Meteor.subscribe('menulist');
      return {
            menuList: Menus.find().fetch(),
            menuListSub: menuListSub,
            menuListSubReady: menuListSub.ready()
        }
}, Menu)
```
