### ISSUE TITLE
Crash on app startup

### ISSUE THREAD

**Issue by luixal** [JcBernack/meteor-reactive-aggregate#27]
Hi,

Just added this package to make one aggregation and it was working fine in a local environment, but just after deploy (using mup) to our server, got a crash (not even on subscribing, just on app startup) for memory allocation.

Rolling back to previous version without aggregation does work fine so... it has something to do with this :(

Guess is due to observer or something related to reactivity because when using meteorhacks aggregate don't get this error (it's not a subscription although).

In case you need more info, the aggregation I'm using is the one in issue #26 

Thanks!

**Comment by JcBernack** [comment]
Very strange. Do you have an error message with more details? Did you try a more simple aggregation to see if it has something to do with your aggregation?

**Comment by luixal** [comment]
Don't have right now, had to go without reactiveness for aggregations. If I try it any other time, I'll post a full log here.

Thanks!
