### ISSUE TITLE
Fetching all documents in collection

### ISSUE THREAD

**Issue by mikkelsjolin** [JcBernack/meteor-reactive-aggregate#28]
I'm trying to figure out why my application is fetching all the documents in my collections.

I have a publication that looks like this:
```
Meteor.publish('location_updates', function(){

  let pipeline = [
    {
      $match: {
        userId: this.userId
      }
    },
    {
      $sort: {
        'location.timestamp': -1
      }
    },
    {
      $limit: 1
    },
    {
      $project: {
        'location.coords': 1,
        'location.uuid': 1
      }
    }
  ];

  ReactiveAggregate(this, Location_updates, pipeline);

});
```

On the client-side I'm selecting a single document:
```
this.subscribe('location_updates');
....
Location_updates.find({'location.uuid': pos.uuid}, { limit: 1 });
```

Yet in the Galaxy APM I'm seeing this when I load the app:

![image](https://user-images.githubusercontent.com/1090770/27187710-3103ae5a-51ec-11e7-8081-b8e9cfb33398.png)

That's every single document in the **location_updates** collection.

The same goes for all my other publications that use ReactiveAggregate.

**Comment by JcBernack** [comment]
See here #18 

I don't know if this is possible by now, but when this package was written aggregation-cursors could not be watched with Meteors `observeChanges`. Thus, to get notified when the aggregation has to be updated a separate query is build which should contain all documents which might affect the aggregation. This query can be supplied with the `observeSelector` and `observeOptions` options. If nothing is given it watches the whole collection, which will cause the behavior you are seeing.

**Comment by mikkelsjolin** [comment]
@JcBernack, you are my hero! 🎉

Thank you for pointing me in the right direction and thank you for this awesome package!
