### ISSUE TITLE
Is the any chance that the package does not work in test mode ?

### ISSUE THREAD

**Issue by Segev95** [JcBernack/meteor-reactive-aggregate#31]
I use `ReactiveAggregate` in publlication. It work fine when I run it but in test mode it does not work for some reason.

Any Idea why ?

**Comment by JcBernack** [comment]
Sorry, no idea why that is not working. If normal publications are no problem it should work, I guess.

**Comment by mdorn** [comment]
@Segev95 -- if you're having the same problem I'm having it's not so much "test mode" that's causing it, it's the fact that [Stub Collections](https://atmospherejs.com/hwillson/stub-collections) does not work with `ReactiveAggregate`.
