### ISSUE TITLE
Single document published

### ISSUE THREAD

**Issue by carlovenus** [JcBernack/meteor-reactive-aggregate#32]
Hi there

i am new to Meteor, so it might be that i am missing out some basics here.
I am using the package to publish the result of a $lookup + $project + $match aggregation to a reactive native app. 
The magic is that, on the react side (within createContainer()), i am getting an array of only one document.
If instead put a $group alone in the pipeline, i get all the expected documents (13).
I am using publish/subscribe on other collections (without aggregation), and they work just fine.
Thanks in advance.

**Comment by JcBernack** [comment]
Closing old issues.

**Comment by kat-serumola** [comment]
Hi there.

What is solution to this issue? Im stuck with it...
