### ISSUE TITLE
Does this method works reactively on server?

### ISSUE THREAD

**Issue by habib786** [JcBernack/meteor-reactive-aggregate#34]
Hello, 
I want to ask about this package. 
If I query collection by using this reactively method, will be it reactively too on the server or not?

**Comment by leite08** [comment]
Hi @habib786 !

I've just finished getting this to work on my application and this is what I found out:

- it is reactive on publications for the main collection
- it is **not** reactive on publications for the joined collections

This means that for this situation...
```
Parent: {
  name: '...',
  childrenIds: [...]
}
Child: {
  name: '...'
}
```
...it will not re-render the component on the UI if the name of a Child changes.

It will, though, update the UI if the name of the Parent changes. In this scenario, the update will include any changes on the Child as well.

Is this the expected current behaviour, @JcBernack? _(by the way, thanks for this package!)_

**Comment by rkstar** [comment]
this is solved by PR https://github.com/JcBernack/meteor-reactive-aggregate/pull/24
