### ISSUE TITLE
$lookup returning empty array

### ISSUE THREAD

**Issue by nosajoahs** [JcBernack/meteor-reactive-aggregate#38]
`a = new Mongo.Collection('a');`
`b= new Mongo.Collection('b');`
`c= new Mongo.Collection('c');`
`d= new Mongo.Collection('d');`

`a.insert({
              "aaa":"hey"
              "aa":'1'
            });`
`b.insert({
              "bbb":"hi"
              "bb": '1'
            });`

`Meteor.publish("c", function () {`
    `const pipeline = [{`
       `$lookup: {`
            `from: 'b',
            localField: 'aa',
            foreignField: 'bb',
            as: 'ab',
        }
    }];`
    `ReactiveAggregate(this, a, pipeline, { clientCollection: "d" });`
`});`

when i return 'd' it returns  
`{"aaa":"hey"
  "aa":'1'
  "ab": []
}`

although "ab" should have `"aaa": "hey"` I believe?

**Comment by ralphievolt** [comment]
Try running a server console log without ReactiveAggregate first to see if your $`lookup` is giving you the correct result

**Comment by JcBernack** [comment]
Closing old issues.
