### ISSUE TITLE
Problem with Methods deletetion

### ISSUE THREAD

**Issue by pedrolucasoliva** [JcBernack/meteor-reactive-aggregate#39]
When I delete a record by Meteor Methods, the reactive don't push the update.
When a do something directly in mongodb, it does normally. I forgot some configuration?

**Comment by pedrolucasoliva** [comment]
Someone pass through this problem? After delete a document at Mongo (Meteor method based), it not comeback with reactive and stuck at my screen. The user think that not "well clicked" and send delete again. Then, Meteor error happens because there is not document to delete. I think thats is some problem whith cache. But I can't resolve. :(

**Comment by JcBernack** [comment]
Can you double check that it works when you delete something directly in MongoDB, but doesn't work when you do the same via a Meteor method? That seems odd to me.

**Comment by pedrolucasoliva** [comment]
@JcBernack, thank you for your attention.
I did check again. Now, I deleted manually a document at mongodb and it doesn't goes to reactivity.
It's a normal behavior or I missed some configuration?

**Comment by JcBernack** [comment]
Ok, can you show some code of how you use reactive aggregation? Do you use `observeSelector` or `lookupCollections`? If you're doing something wrong here the aggregation might miss certain updates.

**Comment by pedrolucasoliva** [comment]
I did Meteor downgrade to 1.6.1.4 and works good.

However, my code:
My publication:
`Meteor.publish('entities', function () {
  if (!this.userId) {
    return;
  }
  ReactiveAggregate(this, Entities.collection, [
    {
      $match: {
        company: Meteor.user().profile.activeCompany,
        type: { $nin: [EntityType.company] }
      }
    },
    {
      $lookup: {
        from: "users",
        localField: "user",
        foreignField: "_id",
        as: "user"
      }
    }
  ]);
});`

My Collection:
`export const Entities = new MongoObservable.Collection<Entity>('entities');`

and my subscription:

`this.dataSub = MeteorObservable.subscribe(this.service).subscribe();
this.data = this.collection.find();`

**Comment by pedrolucasoliva** [comment]
I think that reactive don't works well with npm-mongo 3+.
There are another issues with it: [https://github.com/meteor/meteor/issues/9944](url)

**Comment by pedrolucasoliva** [comment]
#44 It's related?

**Comment by pedrolucasoliva** [comment]
I had try at Meteor 1.8, didnt work too. Sadly I got had to stop at Meteor 1.6.1.3 to keep the Meter Reactive Aggregate working.

**Comment by AlanOrtega91** [comment]
Was this issue ever resolved? I´m having the same problem

**Comment by pedrolucasoliva** [comment]
Is not. I think it's a problem with the new Mongo drive. I'm keeping METEOR 1.6.1.3 in the production environment.

**Comment by Cerealkillerway** [comment]
I have the same problem too... Any news about this one?

**Comment by fishsaidno** [comment]
#44 resolves this issue. We have been using that fork as a local package since the release of Meteor 1.7 to keep things moving.

**Comment by pedrolucasoliva** [comment]
I forked this repo:
meteor add pedrolucasoliva:reactive-aggregate
This works on.
Thanks @FishSaidNo ans @JcBernack.

**Comment by castasamu** [comment]
I have same problem!! :(
When I remove an item reactivity doesn't work.

**Comment by JcBernack** [comment]
Closing old issues.
