### ISSUE TITLE
Non-existent document for aggregation

### ISSUE THREAD

**Issue by seanmavley** [JcBernack/meteor-reactive-aggregate#4]
A document was available for aggregation. That document was deleted. Reactive Aggregate throws this error:

I20160104-10:50:28.341(0)? Exception in queued task: Error: Removed nonexistent document 1
I20160104-10:50:28.342(0)?     at [object Object]._.extend.removed (livedata_server.js:199:17)
I20160104-10:50:28.342(0)?     at [object Object]._.extend.removed (livedata_server.js:388:10)
I20160104-10:50:28.342(0)?     at [object Object]._.extend.removed (livedata_server.js:1269:19)
I20160104-10:50:28.342(0)?     at packages/jcbernack_reactive-aggregate/aggregate.js:27:1
I20160104-10:50:28.342(0)?     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
I20160104-10:50:28.343(0)?     at update (packages/jcbernack_reactive-aggregate/aggregate.js:24:1)
I20160104-10:50:28.343(0)?     at packages/mongo/observe_multiplex.js:183:1
I20160104-10:50:28.343(0)?     at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
I20160104-10:50:28.343(0)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20160104-10:50:28.343(0)?     at Object.task (packages/mongo/observe_multiplex.js:177:1)

Is this issue coming from reactive aggregation?

The error comes up in server console, and doesn't break anything or prevent startup

**Comment by JcBernack** [comment]
Do you have another subscription which is publishing data into the same collection?
Then you may have a problem similar to this one: http://stackoverflow.com/questions/17743937/this-removedcollection-id-makes-somewhere-exception-thrown
If not, I'm not sure what is causing it.

**Comment by seanmavley** [comment]
I'll look into it and let you know.

**Comment by seanmavley** [comment]
I think your hint was the culprit. Got it resolved.
thanks
