### ISSUE TITLE
Add the ability to stop and restart aggregation

### ISSUE THREAD

**Issue by Sergeeeek** [JcBernack/meteor-reactive-aggregate#41]
It would be very useful to be able to restart aggregation in cases when you want to observe some unrelated changes which serve as an input to the aggregation for example.

As for implementation, I think returning a cleanup function from ReactiveAggregate would work.

If you like this idea I can help implement it.

Thoughts?

**Comment by Sergeeeek** [comment]
Or maybe just update the query

**Comment by JcBernack** [comment]
Closing old issues.
