### ISSUE TITLE
returned with empty 

### ISSUE THREAD

**Issue by SaiAravind112** [JcBernack/meteor-reactive-aggregate#42]
//server side code
`UserLogging = new Mongo.Collection('user_logging');

const options = {
    observeOptions: {
        limit: 10,
        sort: { createdAt: -1 },
    }
};

Meteor.publish("reportTotals", function() {
    // Remember, ReactiveAggregate doesn't return anything
    ReactiveAggregate(this, UserLogging, [{
        // assuming our Reports collection have the fields: hours, books
        $group: {
            '_id': "$userId",
            count: {
            // In this case, we're running summation.
                $sum: 1
            }
        }
    }, {
        $project: {
            // an id can be added here, but when omitted,
            // it is created automatically on the fly for you
            userId:'$userId',
            count: '$count'
        } // Send the aggregation to the 'clientReport' collection available for client use
    },options], { clientCollection: "ClientUser" });
});`
//client side code

`ClientUser = new Mongo.Collection('clientuser');

Meteor.subscribe("reportTotals");
  	console.log("**************hllojj**********");

Template.userList.helpers({
  user: function() {
  	console.log("**************hllojj**********");

  	return UserLogging.find({},{limit:20});
  }
});
`
you may have understood what iam doing right...
it is returning with empty 
can you please suggest anything..
any new mwthods to achieve reactive publish is also works...
thanks in advance

**Comment by JcBernack** [comment]
Closing old issues.
