### ISSUE TITLE
Can't combine reactive publish with plain cursor

### ISSUE THREAD

**Issue by Torgen** [JcBernack/meteor-reactive-aggregate#43]
Normally a Publish method can return an array of cursors to publish results from multiple collections. However, since ReactiveAggregate uses the added/changed/removed interface directly, its result can't be combined with a cursor, or another aggregation, as part of a single publish. Either a version of the interface that returns a Cursor should be provided, or ReactiveAggregate should be able to take some cursors to push to the client along with the aggregated data.

**Comment by ralphievolt** [comment]
@Torgen can you show us a sample code?

**Comment by Torgen** [comment]
Like with a regular publish, you can return

```
[Collection1.find(query1), Collection2.find(query2), ...]
```

 like in the docs at https://docs.meteor.com/api/pubsub.html. I'm imagining returning something like

```
[Collection1.find(query1), ReactiveAggregateCursor(this, Collection2, pipeline), ...]
```
to combine a plain query with the result of an aggregation in a single publish, or possibly multiple aggregations.

**Comment by ralphievolt** [comment]
is not the mongodb $lookup function can do this and pass it to ReactiveAggregate?

**Comment by Torgen** [comment]
I'm not trying to join Collection1 with the result of the aggregation.

**Comment by JcBernack** [comment]
Closing old issues.
