### ISSUE TITLE
TypeError: Object [object global] has no method 'added'

### ISSUE THREAD

**Issue by ghost** [JcBernack/meteor-reactive-aggregate#5]
I'm getting this issue:

`I20160130-20:56:41.779(11)? Exception from sub competitionLadders id MkTteTfRnqRasF35S TypeError: Object [object global] has no method 'added'
I20160130-20:56:41.779(11)?     at packages/jcbernack_reactive-aggregate/aggregate.js:17:1
I20160130-20:56:41.779(11)?     at Array.forEach (native)
I20160130-20:56:41.779(11)?     at update (packages/jcbernack_reactive-aggregate/aggregate.js:15:1)
I20160130-20:56:41.779(11)?     at ReactiveAggregate (packages/jcbernack_reactive-aggregate/aggregate.js:47:1)
I20160130-20:56:41.779(11)?     at [object Object]._handler (server/publications/competitions.js:182:5)`

I have set up `competitionLadders` as a client side collection.

This is in my publication:

`ReactiveAggregate(this, CompetitionFixtures, pipeline, {clientCollection : 'competitionLadders'});`

And ideas about the error message?

**Comment by JcBernack** [comment]
Are you sure the `this` argument is the subscription?

It should look something like this

```
Meteor.publish("ladders", function() {
  ReactiveAggregate(this, CompetitionFixtures, pipeline, {clientCollection : 'competitionLadders'});
});
```

**Comment by ghost** [comment]
Thanks @JcBernack. Yeah, I was using the ES6 arrow function syntax for my publication. This seemed to cause problems with the scoping of `this`.
