### ISSUE TITLE
Need for a new version number ? 

### ISSUE THREAD

**Issue by renanlecaro** [JcBernack/meteor-reactive-aggregate#57]
Hi,

Thanks for this great lib. 

I've adopted it in my project, and found a bug with the "subscription.ready()" method being called too early. It seems like it's already been fixed in this repo, but no new version has been published, so people installing the package don't get the bugfix, is that correct ? 

In the meantime I've copied and pasted the code in my own repo. 

If you are not working on this anymore I'd totally understand

**Comment by JcBernack** [comment]
Hi,

that may well be the case, yes.
And yes, I'm not working on this anymore. I have not used Meteor in a very long time and have not kept up to date with their ecosystem.

There are alternatives based on this package which will probably work better for you, like this one:
https://github.com/robfallows/tunguska-reactive-aggregate/
