### ISSUE TITLE
reactive aggregation with React

### ISSUE THREAD

**Issue by davelab** [JcBernack/meteor-reactive-aggregate#7]
does the package support react implementation for meteor?

I'm trying to using it with the mixin ReactMeteorData but i can't retrieve the aggragation data

**Comment by JcBernack** [comment]
I have not used React with Meteor yet, but from what I see it should work. Post some code if you're still having problems.

**Comment by ralphievolt** [comment]
I just saw this package tonight after I did some aggregation in React.. I'll get back to you tomorrow how my test goes.... i'm confident it will work

**Comment by ralphievolt** [comment]
it's working on react but I am not using mixin instead I used Tracker [https://github.com/studiointeract/tracker-component](url)

**Comment by JcBernack** [comment]
@ralphievolt thanks for the info :+1:

**Comment by ralphievolt** [comment]
Fixes #7

**Comment by tim-phillips** [comment]
I'm using this in React using [react-komposer](https://github.com/kadirahq/react-komposer) and it's amazing. Thanks for all the good work!
