### ISSUE TITLE
Two collections in one aggregate method

### ISSUE THREAD

**Issue by Ajaxsoap** [JcBernack/meteor-reactive-aggregate#8]
Hi @JcBernack ,

First of all thanks for this package! It make all my aggregate reactive! :+1: 

is it possible to aggregate two collections in one publication?

Use case:
I have `productName` and `premium` fields in `enrollments` collection.
I have `status`, `products` and `amountPaid` on `claim` collection.

I want to calculate the `loss ratio` = `total money retained`, here's the formula.

`(sum of all premium / sum of all amount paid) * 100 = money retained in %`

the `productName` field from collection 1 and `products` field from collection 2 is basically the same, they are foreign keys from `products` collection as well as `premium`.

I've successfully aggregated/calculated `money retained` per product that matches a certain `status` if `premium` is on `claim` collection but the problem is it will only calculate the total premium of all matching status, the requirement is for all the products(productName) availed in `enrollments` collection.

Here's my working code:

```
Meteor.publish( "lossRatio", function () {
  ReactiveAggregate( this, Claim, [ {
    $match: {
      $or: [ {
        'status': "ApprovedRB"
      }, {
        'status': "Approved"
      } ]
    }
  }, {
    $group: {
      '_id': "$products",
      'amountPaid': {
        $sum: '$amountPaid'
      },
      'premium': {
        $sum: '$premium'
      }
    }
  }, {
    $project: {
      status: '$status',
      amountPaid: '$amountPaid',
      premium: '$premium',
      retained: {
        $multiply: [ {
          $divide: [ '$premium', '$amountPaid' ],
        }, 100 ]
      }

    },
  } ], {
    clientCollection: "LossRatio"
  } );
} );
```

Notice the premium is in `claim` collection but I mentioned earlier that it is on `enrollments` collection, this is for testing purposes to see if will work and it works. 

The issue is that the calculated total `premium` should be based on the total `productName` on `enrollments` collection not the total `products` with matching `status` on `claim` collection. 

Is this possible? I am thinking of creating two separate publications and combine them in one collection. Is this theory possible?

**Comment by JcBernack** [comment]
Hi,

I'm glad you like the package! :)

Unfortunately it will not be of much help beyond what you already achieved. You basically need a join on two collections. Mongo doesn't support that and it is out of scope for this package.

Like you said, you could create two separate publications. Those would end up in two separate collections on the client which you could combine manually to calculate the `money retained`.

**Comment by Ajaxsoap** [comment]
Yup, i manually created two publications and store in the same client collection. It's working on my other publication using your package reactively! I will post my solution here when i'm done :)

I will leave this issue open until I post my solution so that others can benefit.

Thanks again! :+1:

**Comment by ralphievolt** [comment]
@Ajaxsoap do you have any update on your posted solution?

**Comment by Ajaxsoap** [comment]
Hello @ralphievolt,

Sorry for late reponse as i'm pre occupied with all my projects.

Here's my code for two pub and combine in one collection (client).

Below code is for filtering all status with `Approved` and  `ApprovedRB` value and store it on `BranchClaimCount` client collection. 

```
Meteor.publish( "BranchClaimApprovedCount", function () {
    ReactiveAggregate( this, Claim, [ {
      $match: {
        'createdBy': this.userId,
        $or: [ {
          'status': "ApprovedRB"
        }, {
          'status': "Approved"
        } ]
      }
    }, {
      $group: {
        '_id': "$branch",
        totalApproved: {
          $sum: 1
        }
      }
    } ], {
      clientCollection: "BranchClaimCount"
    } );
} );
```

and here's the other code for filtering all status with `Denied` and  `DeniedRB` value and store it on `BranchClaimCount` client collection. 

```
Meteor.publish( "BranchClaimDeniedCount", function () {
    ReactiveAggregate( this, Claim, [ {
      $match: {
        'createdBy': this.userId,
        $or: [ {
          'status': "Denied"
        }, {
          'status': "DeniedRB"
        } ]
      }
    }, {
      $group: {
        '_id': "$branch",
        totalDenied: {
          $sum: 1
        }
      }
    } ], {
      clientCollection: "BranchClaimCount"
    } );
} );
```

Lastly, for the total number of claims:

```
Meteor.publish( "BranchClaimCount", function () {
    ReactiveAggregate( this, Claim, [ {
      $match: {
        'createdBy': this.userId
      }
    }, {
      $group: {
        '_id': "$branch",
        total: {
          $sum: 1
        }
      }
    } ], {
      clientCollection: "BranchClaimCount"
    } );
} );
```

Here's how the document look like:

```
{
  "_id": "LytDnsbXK2d4cgYPX",
  "total": 3,
  "totalApproved": 2,
  "totalDenied": 1
}
```

Client Helpers

```
Template.claimList.helpers( {
  branchName: function ( branch ) {
    var Branch = Branches.findOne( branch );
    if ( Branch ) {
      return Branch && Branch.branch;
    }
  },
  branchClaimsCounts: function () {
    return BranchClaimCount.find();
  }
} );
```

Here's my template code:

```
<template name="claimList">
  {{#if Template.subscriptionsReady}}
  {{#each branchClaimsCounts }}
    <tr>
      <td>{{ branchName _id }}</td>
      <td>{{ total }}</td>
      <td>{{ totalApproved}}  </td>
      <td>{{ totalDenied }}</td>
    </tr>
  {{/each}}
  {{else}}
    {{> loader}}
  {{/if}}
</template>
```

I don't know other approach other than this. 

I hope this helps.

**Comment by Type1J** [comment]
Aggregates have the $lookup operator after MongoDB 3.0
