### ISSUE TITLE
update() should be throttled

### ISSUE THREAD

**Issue by jedwards1211** [JcBernack/meteor-reactive-aggregate#9]
The way this is written, if a collection has 100 documents, `collection.aggregate` will get called 100 times in quick succession, once for every document that's added initially :smile:

It should really be throttled with a customizable wait time, and it would be ideal if it could wait until the all the initial documents have been added, but unfortunately there's no way to know when `observeChanges` is ready...

**Comment by jedwards1211** [comment]
I'll PR this later

**Comment by jedwards1211** [comment]
And note: just using `_.throttle` unfortunately won't work, because `wrapAsync` code must always be run within a `Fiber`.  A thorough solution would wait for the Fiber to finish before running another aggregate, **and** throttle if each Fiber finishes quickly enough.

**Comment by JcBernack** [comment]
All events fired by observeChanges for documents already in the collection on startup are skipped and aggregate is called only once. After that you're totally right. If 100 documents are added aggregate will get called for each insert in quick succession. A proper throttle would be great.

**Comment by jedwards1211** [comment]
Yeah, I totally forgot about the `initialized` flag, that's true.

**Comment by jedwards1211** [comment]
The patch is [here](https://github.com/mindfront/meteor-reactive-aggregate/tree/throttle-patch) but I haven't had time to write tests yet

**Comment by rkstar** [comment]
@jedwards1211 i had a look at [your throttle update](https://github.com/jcoreio/meteor-reactive-aggregate/tree/throttle-patch) and it looks solid. why did you never PR this? i think you should.

**Comment by jedwards1211** [comment]
Oh, I just made the PR, then realized I hadn't because I never got around to writing tests.
Oh well, no tests here anyway...

**Comment by JcBernack** [comment]
see PR #35
